### ISSUE TITLE
AttributeError: module 'matcha.models' has no attribute 'matcha_tts'

### ISSUE THREAD

**Issue by phongnt6192** [phineas-pta/speech-synthesis-ngngngan#3]
Cho mình hỏi, sau khi mình chạy 
train: python matcha/train.py experiment=matcha_ngngngan

===>
Thì bị bão lỗi như này, bạn chỉ cách fix giúp mình với!
\anaconda3\envs\matcha39\lib\site-packages\hydra\_internal\utils.py", line 644, in _locate
    obj = getattr(obj, part)
AttributeError: module 'matcha.models' has no attribute 'matcha_tts'

During handling of the above exception, another exception occurred:

**Comment by phineas-pta** [comment]
bạn có thể cho bik bạn setup `matcha_tts` như thế nào

**Comment by phongnt6192** [comment]
<img width="526" alt="Screenshot 2024-09-16 at 19 51 29" src="https://github.com/user-attachments/assets/fe6c3eef-9355-4178-b1dd-015df0f5a3af">

FIle requirements.txt của Matcha TTS

<img width="1100" alt="Screenshot 2024-09-16 at 19 53 34" src="https://github.com/user-attachments/assets/7f78280d-47e8-476d-8ead-2461dcb29a01">
File Matcha-TTS\configs\data\matcha_ngngngan.yaml

<img width="790" alt="Screenshot 2024-09-16 at 20 06 33" src="https://github.com/user-attachments/assets/cf4dd2bd-69dd-4371-be3f-88469ba4b27c">
Flie Matcha-TTS\configs\experiment\matcha_ngngngan.yaml

<img width="1065" alt="Screenshot 2024-09-16 at 20 07 55" src="https://github.com/user-attachments/assets/e39552ce-77a8-40fa-8a96-dc07751dd68d">
FIle speech-synthesis-ngngngan\data\99-audio-text-file-list\ngngngan_audio_text_train_filelist.txt

<img width="1095" alt="Screenshot 2024-09-16 at 20 08 57" src="https://github.com/user-attachments/assets/3b7e5e03-be6b-4ac6-9c12-e9f46ec2f637">
FIle speech-synthesis-ngngngan\data\99-audio-text-file-list\ngngngan_audio_text_train_filelist.txt.cleaned

File \Matcha-TTS\matcha\text\cleaners.py
Matcha-TTS\matcha\text\symbols.py

đã làm như bạn hướng dẫn
from speech-synthesis-ngngngan/scripts/_cleaner.py to Matcha-TTS/matcha/text/cleaners.py
from speech-synthesis-ngngngan/scripts/_symbols.py to Matcha-TTS/matcha/text/symbols.py

File Matcha-TTS\matcha\cli.py
<img width="730" alt="Screenshot 2024-09-16 at 20 13 34" src="https://github.com/user-attachments/assets/b4383995-bff8-4eff-85aa-9f2207f8fe50">


run python matcha/utils/generate_data_statistics.py -i matcha_ngngngan.yaml (remember edit file path)
get 2 values mel_mean & mel_std then go back edit file matcha_ngngngan.yaml (should be correct already)
mình đã thay 2 giá trị này vào rồi.
Mình dùng python version 3.10 3.9 đều bị lỗi trên

<img width="816" alt="Screenshot 2024-09-16 at 21 02 05" src="https://github.com/user-attachments/assets/f6ade62b-5cd4-4bbb-bca5-2bcf8bbaab99">
Matcha-TTS\synthesis.ipynb chạy file này cũng bị báo lỗi như trên
Bạn xem giúp mình với

**Comment by phineas-pta** [comment]
lúc chạy lệnh này bạn có gặp lỗi ko
![image](https://github.com/user-attachments/assets/091d04e4-5eeb-4906-be11-a9218e7c4ef2)

**Comment by phongnt6192** [comment]
nếu mình giữ nguyên phải
[requirements.txt](https://github.com/shivammehta25/Matcha-TTS/blob/main/requirements.txt)
và update như bạn hướng dãn thì sẽ bị lỗi nhưng mình lấy theo như file  requirements.txt bên trên của mình thì ok.
Tuy nhiên khi chạy xong rồi thử 
matcha-tts --text "<INPUT TEXT>"
thì báo lỗi numpy
<img width="879" alt="Screenshot 2024-09-16 at 21 33 08" src="https://github.com/user-attachments/assets/39fe6a1e-ef2f-40dd-8194-457a997ea4ea">

**Comment by phineas-pta** [comment]
> update như bạn hướng dãn thì sẽ bị lỗi

bạn bị lỗi j mới dc

còn lỗi trong hình thì phải downgrade `numpy` xuống 1.26.4

**Comment by phongnt6192** [comment]
Có vẻ lúc trước do lỗi cài các package của mình rồi.
Mình mới xóa hết các thư viện đi xong chạy lại thì báo cài matcha-tts thành công rồi
nhưng sau mình chạy lệnh 
train: python matcha/train.py experiment=matcha_ngngngan
thì lại bị lỗi này, bạn có thể xem giúp mình đc không.
<img width="1480" alt="Screenshot 2024-09-16 at 22 24 03" src="https://github.com/user-attachments/assets/c78a40c1-e675-426b-8516-5fec73da41e3">
lỗi này là có phải cần thêm pytorch phải k bạn
<img width="828" alt="Screenshot 2024-09-16 at 22 30 29" src="https://github.com/user-attachments/assets/4843ab37-d5aa-4ed6-88d9-985a1a70f667">
và nếu phải cài thì dùng version này có đúng k bạn?
# CUDA 11.6
conda install pytorch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 pytorch-cuda=11.6 -c pytorch -c nvidia
MÌnh có thể kết bạn với bạn qua zalo hoặc mes được không
cám ơn bạn rất nhiều!

**Comment by phineas-pta** [comment]
mình trả lời tin nhắn chậm lắm, bữa nay rảnh tay nên mới rep bạn nhanh như vậy, chứ ko bt để qua ngày mới rep

còn cuda thì bạn đã cài ở system level (cmd nhận `nvcc`) r thì ko cần cài thêm ở conda nữa

cách cài thì tuỳ ng thôi, bt thì mình sẽ khởi tạo 1 conda env trống chỉ với mỗi python, sau đó dùng `pip` để cài `torch` các kiểu, tại vì cài `torch` với conda có 2 channels hơi lằng nhằng

**Comment by phongnt6192** [comment]
Vâng cám ơn bạn
nhưng cho mình hỏi thêm lỗi như này thì cần cài đặt thêm gì hay config gì thêm không bạn?
![image](https://github.com/user-attachments/assets/768feff1-d1fd-4e02-a86d-a9cbd0dec377)

**Comment by phineas-pta** [comment]
chủ yếu là do setup cuda + pytorch thôi, 1 khi torch nhận dc cuda r thì tự động cái `lightning` nhận

check cũng dễ: chạy lệnh `python -c "import torch; print(torch.cuda.is_available())"` ra `True` là cài ok

**Comment by phongnt6192** [comment]
Cám ơn bạn đã hỗ trợ mình, mình đã cái thành công rồi, mình dang train thử.
có gì bạn hỗ trợ thêm cho mình với nhé!
Cám ơn bạn nhiều!

**Comment by phineas-pta** [comment]
ok bạn 🤗
